site_name: BXI_Wiki
site_description: an example blog set up following the tutorial
site_url: https://wiki.bxirobotics.cn

theme:
  name: material
  logo: assets/other/logo.png
  favicon: assets/other/logo.png
  icon:
    alternate: material/translate
  features:
    - navigation.tabs
    - navigation.top
  palette:
    # 浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换到暗色模式

    # 深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch
        name: 切换到亮色模式

extra:
  alternate:
    - name: 简体中文
      link: /
      lang: zh
    - name: English
      link: /en/
      lang: en

repo_name: MineSunshineone/BXI_Wiki
repo_url: https://github.com/MineSunshineone/BXI_Wiki
edit_uri: edit/main/docs/

plugins:
  - search
  - awesome-pages
  - redirects
  - mkdocs-video
  - glightbox
  - git-authors
  - minify:
      minify_html: true
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: zh
          default: true
          name: 简体中文
        - locale: en
          name: English
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - 首页: zh/index.md
  - ELF3:
      - 概览: zh/elf3/index.md
      - 快速入门: zh/elf3/quick_start.md
  - 关节模组:
      - 概览: zh/joint_module/index.md
  - 强化学习:
      - 概览: zh/rl/index.md
  - 重映射:
      - 概览: zh/remapping/index.md
  - 其他:
      - 概览: zh/others/index.md
